In [9]:
import pandas as pd
import sqlalchemy
import pymysql
from matplotlib.pyplot import plot

In [42]:
conn=sqlalchemy.create_engine("mysql+pymysql://root:ma291188@localhost/leetcode")
products=pd.read_sql_table(con=conn,table_name="products")
orders=pd.read_sql_table(con=conn,table_name="invoice")

In [43]:
producs

    index  product_id  price
0       0           1    215
1       1           2    321
2       2           3    414
3       3           4    204
4       4           5    103
5       5           6    373
6       6           7    258
7       7           8    426
8       8           9    193
9       9          10    155
10     10          11    387
11     11          12    358
12     12          13    222
13     13          14    287
14     14          15    152
15     15          16    130
16     16          17    102
17     17          18    202
18     18          19    370
19     19          20    240

In [44]:
order_buy_id={}
for i in range(len(orders)):
    row=orders.iloc[i]
    print(row)
    _id=products.loc[row.product_id].product_id
    price=products.loc[row.product_id].price
    if _id not in res:
        res[_id]=[]
    res[_id].append(price)

index          0
invoice_id     4
product_id    14
quantity       6
Name: 0, dtype: int64
index          1
invoice_id     6
product_id    17
quantity       2
Name: 1, dtype: int64
index         2
invoice_id    9
product_id    5
quantity      4
Name: 2, dtype: int64
index          3
invoice_id    10
product_id    14
quantity       7
Name: 3, dtype: int64
index          4
invoice_id    16
product_id    19
quantity       8
Name: 4, dtype: int64
index          5
invoice_id    10
product_id     6
quantity       5
Name: 5, dtype: int64
index          6
invoice_id    17
product_id     4
quantity       9
Name: 6, dtype: int64
index          7
invoice_id     3
product_id    16
quantity       9
Name: 7, dtype: int64
index          8
invoice_id    15
product_id     3
quantity       1
Name: 8, dtype: int64
index          9
invoice_id     6
product_id    14
quantity       5
Name: 9, dtype: int64
index         10
invoice_id    15
product_id     9
quantity       7
Name: 10, dtype: int64
index         11
invoice_id     8
product_id     6
quantity       4
Name: 11, dtype: int64
index         12
invoice_id    15
product_id    15
quantity       7
Name: 12, dtype: int64
index         13
invoice_id     5
product_id     1
quantity       3
Name: 13, dtype: int64
index         14
invoice_id    12
product_id    13
quantity       2
Name: 14, dtype: int64
index         15
invoice_id     5
product_id    20
quantity       3
Name: 15, dtype: int64

KeyError: 20